version: '3.8'
services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:5.7.21
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=doca_pets
      - MYSQL_USER=doca_pets
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
      - TZ=Asia/Kuala_Lumpur

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "7000:80"
    links:
      - mysql:db

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    restart: always
    volumes:
      - ./src:/var/www/html:delegated

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: ci4
    entrypoint: ['composer', '--ignore-platform-reqs']

  npm:
    image: node:13.7
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
